# Generated by Django 5.2.11 on 2026-04-27 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_fieldrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmtask',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='task_images/'),
        ),
    ]
