# Generated by Django 5.2.11 on 2026-04-28 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_farmtask_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmtask',
            name='progress_comment',
            field=models.TextField(blank=True),
        ),
    ]
